# config.yaml
matching:
  key_columns:
    - region
    - zone
    - woreda
    - health_facilities
  threshold: 80
  multi_level_threshold: 90

app:
  debug: true
  secret_key: 'your_secret_key_here'
