  usernames:
    Jiregna:
      email: jwirtu@gmail.com
      name: Jiregna Wirtu
      password: '$2b$12$abcd1234abcd1234abcd12'

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
    jwirtu@gmail.com
